version: "3.9"

services:
  backend:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5433:5432

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 81:80
    depends_on:
      - backend

volumes:
  postgres_data:



